export const SEARCH_GITHUBUSER_START = 'SEARCH_GITHUBUSER_START';
export const SEARCH_GITHUBUSER_SUCCESS = 'SEARCH_GITHUBUSER_SUCCESS';
export const SEARCH_GITHUBUSER_FAILED = 'SEARCH_GITHUBUSER_FAILED';

export const LOAD_REPOSITORI_START = 'LOAD_REPOSITORI_START';
export const LOAD_REPOSITORI_SUCCESS = 'LOAD_REPOSITORI_SUCCESS';
export const LOAD_REPOSITORI_FAILED = 'LOAD_REPOSITORI_FAILED';